// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.5
// source: api/v1/lunar.proto

package lunarv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetCalendarRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Date          string                 `protobuf:"bytes,1,opt,name=date,proto3" json:"date,omitempty"` // 格式: YYYY-MM-DD
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCalendarRequest) Reset() {
	*x = GetCalendarRequest{}
	mi := &file_api_v1_lunar_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCalendarRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCalendarRequest) ProtoMessage() {}

func (x *GetCalendarRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_lunar_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCalendarRequest.ProtoReflect.Descriptor instead.
func (*GetCalendarRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_lunar_proto_rawDescGZIP(), []int{0}
}

func (x *GetCalendarRequest) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

type GetCalendarResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GregorianDate string                 `protobuf:"bytes,1,opt,name=gregorian_date,json=gregorianDate,proto3" json:"gregorian_date,omitempty"`
	JulianDay     float64                `protobuf:"fixed64,2,opt,name=julian_day,json=julianDay,proto3" json:"julian_day,omitempty"`
	DeltaT        float64                `protobuf:"fixed64,3,opt,name=delta_t,json=deltaT,proto3" json:"delta_t,omitempty"`
	Lunar         *LunarInfo             `protobuf:"bytes,4,opt,name=lunar,proto3" json:"lunar,omitempty"`
	Buddhist      string                 `protobuf:"bytes,5,opt,name=buddhist,proto3" json:"buddhist,omitempty"`
	Taoist        string                 `protobuf:"bytes,6,opt,name=taoist,proto3" json:"taoist,omitempty"`
	Pillars       *Pillars               `protobuf:"bytes,7,opt,name=pillars,proto3" json:"pillars,omitempty"`
	SolarTerm     *SolarTerm             `protobuf:"bytes,8,opt,name=solar_term,json=solarTerm,proto3" json:"solar_term,omitempty"`
	TwelveOfficer string                 `protobuf:"bytes,9,opt,name=twelve_officer,json=twelveOfficer,proto3" json:"twelve_officer,omitempty"`
	ShenSha       []*ShenSha             `protobuf:"bytes,10,rep,name=shen_sha,json=shenSha,proto3" json:"shen_sha,omitempty"`
	HolidayInfo   *HolidayInfo           `protobuf:"bytes,11,opt,name=holiday_info,json=holidayInfo,proto3" json:"holiday_info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCalendarResponse) Reset() {
	*x = GetCalendarResponse{}
	mi := &file_api_v1_lunar_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCalendarResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCalendarResponse) ProtoMessage() {}

func (x *GetCalendarResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_lunar_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCalendarResponse.ProtoReflect.Descriptor instead.
func (*GetCalendarResponse) Descriptor() ([]byte, []int) {
	return file_api_v1_lunar_proto_rawDescGZIP(), []int{1}
}

func (x *GetCalendarResponse) GetGregorianDate() string {
	if x != nil {
		return x.GregorianDate
	}
	return ""
}

func (x *GetCalendarResponse) GetJulianDay() float64 {
	if x != nil {
		return x.JulianDay
	}
	return 0
}

func (x *GetCalendarResponse) GetDeltaT() float64 {
	if x != nil {
		return x.DeltaT
	}
	return 0
}

func (x *GetCalendarResponse) GetLunar() *LunarInfo {
	if x != nil {
		return x.Lunar
	}
	return nil
}

func (x *GetCalendarResponse) GetBuddhist() string {
	if x != nil {
		return x.Buddhist
	}
	return ""
}

func (x *GetCalendarResponse) GetTaoist() string {
	if x != nil {
		return x.Taoist
	}
	return ""
}

func (x *GetCalendarResponse) GetPillars() *Pillars {
	if x != nil {
		return x.Pillars
	}
	return nil
}

func (x *GetCalendarResponse) GetSolarTerm() *SolarTerm {
	if x != nil {
		return x.SolarTerm
	}
	return nil
}

func (x *GetCalendarResponse) GetTwelveOfficer() string {
	if x != nil {
		return x.TwelveOfficer
	}
	return ""
}

func (x *GetCalendarResponse) GetShenSha() []*ShenSha {
	if x != nil {
		return x.ShenSha
	}
	return nil
}

func (x *GetCalendarResponse) GetHolidayInfo() *HolidayInfo {
	if x != nil {
		return x.HolidayInfo
	}
	return nil
}

type LunarInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Year          int32                  `protobuf:"varint,1,opt,name=year,proto3" json:"year,omitempty"`
	Month         int32                  `protobuf:"varint,2,opt,name=month,proto3" json:"month,omitempty"`
	Day           int32                  `protobuf:"varint,3,opt,name=day,proto3" json:"day,omitempty"`
	IsLeap        bool                   `protobuf:"varint,4,opt,name=is_leap,json=isLeap,proto3" json:"is_leap,omitempty"`
	StringValue   string                 `protobuf:"bytes,5,opt,name=string_value,json=stringValue,proto3" json:"string_value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LunarInfo) Reset() {
	*x = LunarInfo{}
	mi := &file_api_v1_lunar_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LunarInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LunarInfo) ProtoMessage() {}

func (x *LunarInfo) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_lunar_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LunarInfo.ProtoReflect.Descriptor instead.
func (*LunarInfo) Descriptor() ([]byte, []int) {
	return file_api_v1_lunar_proto_rawDescGZIP(), []int{2}
}

func (x *LunarInfo) GetYear() int32 {
	if x != nil {
		return x.Year
	}
	return 0
}

func (x *LunarInfo) GetMonth() int32 {
	if x != nil {
		return x.Month
	}
	return 0
}

func (x *LunarInfo) GetDay() int32 {
	if x != nil {
		return x.Day
	}
	return 0
}

func (x *LunarInfo) GetIsLeap() bool {
	if x != nil {
		return x.IsLeap
	}
	return false
}

func (x *LunarInfo) GetStringValue() string {
	if x != nil {
		return x.StringValue
	}
	return ""
}

type Pillars struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Year          string                 `protobuf:"bytes,1,opt,name=year,proto3" json:"year,omitempty"`
	Month         string                 `protobuf:"bytes,2,opt,name=month,proto3" json:"month,omitempty"`
	Day           string                 `protobuf:"bytes,3,opt,name=day,proto3" json:"day,omitempty"`
	Hour          string                 `protobuf:"bytes,4,opt,name=hour,proto3" json:"hour,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Pillars) Reset() {
	*x = Pillars{}
	mi := &file_api_v1_lunar_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Pillars) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pillars) ProtoMessage() {}

func (x *Pillars) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_lunar_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pillars.ProtoReflect.Descriptor instead.
func (*Pillars) Descriptor() ([]byte, []int) {
	return file_api_v1_lunar_proto_rawDescGZIP(), []int{3}
}

func (x *Pillars) GetYear() string {
	if x != nil {
		return x.Year
	}
	return ""
}

func (x *Pillars) GetMonth() string {
	if x != nil {
		return x.Month
	}
	return ""
}

func (x *Pillars) GetDay() string {
	if x != nil {
		return x.Day
	}
	return ""
}

func (x *Pillars) GetHour() string {
	if x != nil {
		return x.Hour
	}
	return ""
}

type SolarTerm struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Index         int32                  `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Longitude     float64                `protobuf:"fixed64,3,opt,name=longitude,proto3" json:"longitude,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SolarTerm) Reset() {
	*x = SolarTerm{}
	mi := &file_api_v1_lunar_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SolarTerm) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SolarTerm) ProtoMessage() {}

func (x *SolarTerm) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_lunar_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SolarTerm.ProtoReflect.Descriptor instead.
func (*SolarTerm) Descriptor() ([]byte, []int) {
	return file_api_v1_lunar_proto_rawDescGZIP(), []int{4}
}

func (x *SolarTerm) GetIndex() int32 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *SolarTerm) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SolarTerm) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

type ShenSha struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShenSha) Reset() {
	*x = ShenSha{}
	mi := &file_api_v1_lunar_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShenSha) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShenSha) ProtoMessage() {}

func (x *ShenSha) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_lunar_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShenSha.ProtoReflect.Descriptor instead.
func (*ShenSha) Descriptor() ([]byte, []int) {
	return file_api_v1_lunar_proto_rawDescGZIP(), []int{5}
}

func (x *ShenSha) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ShenSha) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type HolidayInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsHoliday     bool                   `protobuf:"varint,1,opt,name=is_holiday,json=isHoliday,proto3" json:"is_holiday,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HolidayInfo) Reset() {
	*x = HolidayInfo{}
	mi := &file_api_v1_lunar_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HolidayInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HolidayInfo) ProtoMessage() {}

func (x *HolidayInfo) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_lunar_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HolidayInfo.ProtoReflect.Descriptor instead.
func (*HolidayInfo) Descriptor() ([]byte, []int) {
	return file_api_v1_lunar_proto_rawDescGZIP(), []int{6}
}

func (x *HolidayInfo) GetIsHoliday() bool {
	if x != nil {
		return x.IsHoliday
	}
	return false
}

func (x *HolidayInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

var File_api_v1_lunar_proto protoreflect.FileDescriptor

const file_api_v1_lunar_proto_rawDesc = "" +
	"\n" +
	"\x12api/v1/lunar.proto\x12\x06api.v1\"(\n" +
	"\x12GetCalendarRequest\x12\x12\n" +
	"\x04date\x18\x01 \x01(\tR\x04date\"\xb9\x03\n" +
	"\x13GetCalendarResponse\x12%\n" +
	"\x0egregorian_date\x18\x01 \x01(\tR\rgregorianDate\x12\x1d\n" +
	"\n" +
	"julian_day\x18\x02 \x01(\x01R\tjulianDay\x12\x17\n" +
	"\adelta_t\x18\x03 \x01(\x01R\x06deltaT\x12'\n" +
	"\x05lunar\x18\x04 \x01(\v2\x11.api.v1.LunarInfoR\x05lunar\x12\x1a\n" +
	"\bbuddhist\x18\x05 \x01(\tR\bbuddhist\x12\x16\n" +
	"\x06taoist\x18\x06 \x01(\tR\x06taoist\x12)\n" +
	"\apillars\x18\a \x01(\v2\x0f.api.v1.PillarsR\apillars\x120\n" +
	"\n" +
	"solar_term\x18\b \x01(\v2\x11.api.v1.SolarTermR\tsolarTerm\x12%\n" +
	"\x0etwelve_officer\x18\t \x01(\tR\rtwelveOfficer\x12*\n" +
	"\bshen_sha\x18\n" +
	" \x03(\v2\x0f.api.v1.ShenShaR\ashenSha\x126\n" +
	"\fholiday_info\x18\v \x01(\v2\x13.api.v1.HolidayInfoR\vholidayInfo\"\x83\x01\n" +
	"\tLunarInfo\x12\x12\n" +
	"\x04year\x18\x01 \x01(\x05R\x04year\x12\x14\n" +
	"\x05month\x18\x02 \x01(\x05R\x05month\x12\x10\n" +
	"\x03day\x18\x03 \x01(\x05R\x03day\x12\x17\n" +
	"\ais_leap\x18\x04 \x01(\bR\x06isLeap\x12!\n" +
	"\fstring_value\x18\x05 \x01(\tR\vstringValue\"Y\n" +
	"\aPillars\x12\x12\n" +
	"\x04year\x18\x01 \x01(\tR\x04year\x12\x14\n" +
	"\x05month\x18\x02 \x01(\tR\x05month\x12\x10\n" +
	"\x03day\x18\x03 \x01(\tR\x03day\x12\x12\n" +
	"\x04hour\x18\x04 \x01(\tR\x04hour\"S\n" +
	"\tSolarTerm\x12\x14\n" +
	"\x05index\x18\x01 \x01(\x05R\x05index\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1c\n" +
	"\tlongitude\x18\x03 \x01(\x01R\tlongitude\"?\n" +
	"\aShenSha\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\"@\n" +
	"\vHolidayInfo\x12\x1d\n" +
	"\n" +
	"is_holiday\x18\x01 \x01(\bR\tisHoliday\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name2V\n" +
	"\fLunarService\x12F\n" +
	"\vGetCalendar\x12\x1a.api.v1.GetCalendarRequest\x1a\x1b.api.v1.GetCalendarResponseB1Z/github.com/kaecer68/lunar-zenith/api/v1;lunarv1b\x06proto3"

var (
	file_api_v1_lunar_proto_rawDescOnce sync.Once
	file_api_v1_lunar_proto_rawDescData []byte
)

func file_api_v1_lunar_proto_rawDescGZIP() []byte {
	file_api_v1_lunar_proto_rawDescOnce.Do(func() {
		file_api_v1_lunar_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_v1_lunar_proto_rawDesc), len(file_api_v1_lunar_proto_rawDesc)))
	})
	return file_api_v1_lunar_proto_rawDescData
}

var file_api_v1_lunar_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_api_v1_lunar_proto_goTypes = []any{
	(*GetCalendarRequest)(nil),  // 0: api.v1.GetCalendarRequest
	(*GetCalendarResponse)(nil), // 1: api.v1.GetCalendarResponse
	(*LunarInfo)(nil),           // 2: api.v1.LunarInfo
	(*Pillars)(nil),             // 3: api.v1.Pillars
	(*SolarTerm)(nil),           // 4: api.v1.SolarTerm
	(*ShenSha)(nil),             // 5: api.v1.ShenSha
	(*HolidayInfo)(nil),         // 6: api.v1.HolidayInfo
}
var file_api_v1_lunar_proto_depIdxs = []int32{
	2, // 0: api.v1.GetCalendarResponse.lunar:type_name -> api.v1.LunarInfo
	3, // 1: api.v1.GetCalendarResponse.pillars:type_name -> api.v1.Pillars
	4, // 2: api.v1.GetCalendarResponse.solar_term:type_name -> api.v1.SolarTerm
	5, // 3: api.v1.GetCalendarResponse.shen_sha:type_name -> api.v1.ShenSha
	6, // 4: api.v1.GetCalendarResponse.holiday_info:type_name -> api.v1.HolidayInfo
	0, // 5: api.v1.LunarService.GetCalendar:input_type -> api.v1.GetCalendarRequest
	1, // 6: api.v1.LunarService.GetCalendar:output_type -> api.v1.GetCalendarResponse
	6, // [6:7] is the sub-list for method output_type
	5, // [5:6] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_api_v1_lunar_proto_init() }
func file_api_v1_lunar_proto_init() {
	if File_api_v1_lunar_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_v1_lunar_proto_rawDesc), len(file_api_v1_lunar_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_v1_lunar_proto_goTypes,
		DependencyIndexes: file_api_v1_lunar_proto_depIdxs,
		MessageInfos:      file_api_v1_lunar_proto_msgTypes,
	}.Build()
	File_api_v1_lunar_proto = out.File
	file_api_v1_lunar_proto_goTypes = nil
	file_api_v1_lunar_proto_depIdxs = nil
}
